org.gradle.jvmargs=-Xmx4G
minecraft_version=26.1.2
archives_base_name=findme
mod_version=4.0.0
maven_group=com.buuz135.findme
fabric_loader_version=0.19.2
fabric_api_version=0.148.0+26.1.2
loom_version=1.16-SNAPSHOT

# HTTP 代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10809

# HTTPS 代理
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10809